services:
  backend:
    env_file: ./backend/.env
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    network_mode: host
    #depends_on:
      #- api
    #networks:
      #- frontend
      #- backend
  frontend:
    build: frontend
    ports:
      - "5173:5173"
    networks:
      - frontend
    volumes:
      - ./frontend/:/app
#  nginx:
#    image: nginx:stable-alpine
#    container_name: nginx
#    restart: always
#    ports:
#      - "8080:8080"
#    volumes: 
#      - ./reverseproxy:/etc/nginx/conf.d/
#    networks:
#      - backend
#      - frontend
#  db:
#    image: mongo
#    # will be running on port 27017
#    networks:
#      - backend
#  api:
#    build: ai
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./ai:/app
#    networks:
#      - backend

networks:
  frontend:
  backend:
